spring:
    application:
        name: gestionmesas

    datasource:
        url: jdbc:mysql://localhost:3306/orderflow-v1-m3
        username: root
        password: ""

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    doc:
        api-docs:
            enabled: true
            version: openapi_3_0
        swagger-ui:
            enabled: true

server:
    port: 8082

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
